fabric_project:
  target: dev
  outputs:
    
    dev:
      type: fabric
      driver: 'ODBC Driver 18 for SQL Server'
      server: '23epkopltczezcxx6egx5mbf54-5cmtoljztobebiyuzv2fzo6yhu.datawarehouse.fabric.microsoft.com'
      database: 'wh_nadir_project'
      schema: dbo
      authentication: CLI

    
    prod:
      type: fabric
      driver: 'ODBC Driver 18 for SQL Server'
      server: '23epkopltczezcxx6egx5mbf54-zw7vvakmmixuzfhqpdcspoiz2q.datawarehouse.fabric.microsoft.com' # <-- Naya Prod Server Link
      database: 'wh_nadir_project_Prod' 
      schema: dbo
      authentication: CLI