CREATE TABLE [gold].[sales_analysis] (

	[sales_id] int NULL, 
	[quantity] int NULL, 
	[unit_price] float NULL, 
	[gross_amount] float NULL, 
	[discount_amount] float NULL, 
	[net_amount] float NULL, 
	[payment_method] varchar(8000) NULL, 
	[discount_tier] varchar(15) NOT NULL, 
	[customer_sk] int NULL, 
	[customer_full_name] varchar(8000) NOT NULL, 
	[customer_email] varchar(8000) NULL, 
	[loyalty_tier] varchar(8000) NULL, 
	[product_sk] int NULL, 
	[product_code] varchar(8000) NULL, 
	[product_name] varchar(8000) NULL, 
	[product_department] varchar(8000) NULL, 
	[product_category] varchar(8000) NULL, 
	[product_list_price] decimal(18,2) NULL, 
	[date_sk] int NULL, 
	[sales_date] date NULL, 
	[sales_year] int NULL, 
	[sales_month] varchar(8000) NULL, 
	[sales_day_name] int NULL
);